ctypedef int (*face_evaluate_fn)(
    void* ctx,
    const double* x,
    double* nll,
    double* gradient,
    double* metric,
    double* smallest,
) noexcept nogil

ctypedef void (*face_accept_fn)(void* ctx) noexcept nogil


cdef struct FaceObjective:
    void* ctx
    face_evaluate_fn evaluate
    face_accept_fn accept


cdef int _in_safeguarded_metric(
    int n,
    const double* fisher,
    const double* missing,
    double* metric,
    double* work,
    double* smallest_out,
) noexcept nogil

cdef int _in_evaluate_raw(
    int n,
    int curvature_degree,
    const double* theta,
    Py_ssize_t Rf,
    const double* finite_intervals,
    const double* finite_weights,
    const double* point_lower_distance,
    const double* point_upper_distance,
    Py_ssize_t Ra,
    const double* adaptive_intervals,
    const double* adaptive_weights,
    double whole_weight,
    double log_coordinate_scale,
    const double* support,
    const double* data_bounds,
    const int* kinds,
    const int* lengths,
    const double* coefficients,
    Py_ssize_t width,
    const double* controls,
    double epsabs,
    double epsrel,
    int limit,
    Py_ssize_t G,
    const double* gl_nodes,
    const double* gl_log_weights,
    double width_eps_mult,
    int lower_index,
    int upper_index,
    double* q_poly,
    double* amplitudes,
    double* state_work,
    double* geometry,
    double* points,
    double* moments,
    double* model_means,
    double* model_fisher,
    double* natural_scale,
    double* log_probability,
    double* obs_h,
    double* obs_cov,
    double* sum_h,
    double* sum_second,
    double* hbuf,
    double* nll,
    double* gradient,
    double* adaptive_log_probability,
    double* finite_row_means,
    double* finite_row_cov,
    double* adaptive_row_means,
    double* adaptive_row_cov,
) noexcept nogil

cdef int _pn_evaluate(
    int n,
    int curvature_degree,
    int lower_index,
    int upper_index,
    const double* theta,
    const double* empirical,
    double coordinate_constant,
    const double* support,
    const double* data_bounds,
    bint featL,
    bint featU,
    const int* kinds,
    const int* lengths,
    const double* coefficients,
    Py_ssize_t width,
    const double* controls,
    double epsabs,
    double epsrel,
    int limit,
    double* q_poly,
    double* amplitudes,
    double* state_work,
    double* geometry,
    double* points,
    double* moments,
    int n_power,
    int n_log,
    int F,
    double* nll,
    double* gradient,
    double* means,
    double* fisher,
) noexcept nogil

cdef int _face_newton_loop(
    int n,
    int r,
    int nb,
    const int* sizes,
    const Py_ssize_t* aoff,
    const Py_ssize_t* qoff,
    Py_ssize_t qtot,
    Py_ssize_t na,
    const double* b,
    const double* a,
    const double* ref,
    const Py_ssize_t* degrees,
    FaceObjective* objective,
    double* theta,
    double* blocks,
    double* current_nll,
    double* gradient,
    double* hessian,
    double* current_smallest,
    double* dual,
    double tolerance,
    double certified_tolerance,
    double accuracy_floor,
    int max_iterations,
    double armijo,
    double backtrack,
    int max_line_search,
    int min_steps,
    int* iterations_out,
    int* evaluations_out,
    int* subproblem_iterations_out,
    double* bound_out,
) noexcept nogil
