cdef api int adaptive_natural_objective_c(
    Py_ssize_t R,
    Py_ssize_t P,
    Py_ssize_t W,
    Py_ssize_t nq,
    const double* intervals,
    const double* row_weights,
    const double* q_poly,
    double a_lower,
    double a_upper,
    double mode,
    double local_scale,
    double log_Z,
    const int* natural_kinds,
    const int* natural_lengths,
    const double* coefficients,
    double support_lower,
    double support_upper,
    double epsabs,
    double epsrel,
    int limit,
    double* log_probability,
    double* obs_h,
    double* obs_cov,
    double* nll_io,
) noexcept nogil
